apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  type: {{ .Values.flask.service.type }}
  selector:
    app: flask-app
  ports:
    - name: http
      port: {{ .Values.flask.service.port }}
      targetPort: {{ .Values.flask.service.targetPort }}
{{- if .Values.flask.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-app
  annotations:
    kubernetes.io/ingress.class: {{ .Values.flask.ingress.className }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: {{ .Values.flask.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-app
                port:
                  number: {{ .Values.flask.service.port }}
{{- end }}
