apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: {{ .Values.flask.replicaCount }}
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: "{{ .Values.flask.image.repository }}:{{ .Values.flask.image.tag }}"
          imagePullPolicy: {{ .Values.flask.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.flask.service.targetPort }}
          envFrom:
            - configMapRef:
                name: flask-config
            - secretRef:
                name: postgres-credentials
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
          resources:
            {{- toYaml .Values.flask.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.flask.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.flask.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
